docs/ktlint.md
Hey together,
we are currently evaluating if these rules can be applied in our project.
We are using the `ktlint-gradle` plugin.
We found the warning for this plugin. It says that ktlint in version 0.46.0 is not support by ktlint-gradle.
Just recently, they added support for this version. See https://github.com/JLLeitschuh/ktlint-gradle/releases/tag/v11.1.0
Therefore I thought it make sense to change the warning to an note 🙃 
Nevertheless, I still don't know **why** it requires a specific ktlint version. Maybe someone can explain this a bit more in detail and I can add more information regarding "a" specific ktlint version?! 🤔 
I have the feeling, because of this, it (ktlint-gradle) now requires to support ktlint 0.48.2 ? 🤔 🤷 
https://github.com/mrmans0n/compose-rules/blob/621eb8a51428ec0d …
=> Change warning for ktlint-gradle

docs/detekt.md, docs/ktlint.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/ComposeModifierMissing.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ComposeModifierMissingCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/EditorConfigProperties.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ComposeCompositionLocalAllowlistCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ComposeModifierMissingCheckTest.kt
Adds configurability to the ModifierMissing rule, so that now users can configure whether they want non-public composables to be also subject to this check. The current configuration, where only public composables run this rule, keeps being the default. Values `public_and_internal` and `all` are added.
Fixes #25
=> Add configuration to the ModifierMissing rule

docs/detekt.md, docs/ktlint.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/ComposeViewModelInjection.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ComposeViewModelInjectionCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/EditorConfigProperties.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ComposeViewModelInjectionCheckTest.kt
Previously, only known ViewModel factories (e.g. "viewModel", "weaverViewModel", "hiltViewModel", "injectedViewModel", "mavericksViewModel") were taking into account when checking for their proper injection in composables.
This patch allows configuration of custom factories in the user codebase.
=> Allow custom configuration of ViewModel factories

core-common/src/main/kotlin/io/nlopez/rules/core/util/KtFunctions.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ComposeCompositionLocalAllowlist.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ComposeNaming.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ComposeNamingCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ComposeNamingCheckTest.kt
ComposeNaming shouldn't be applied if the method is an `operator fun`, as those have fixed names and we can't argue against kotlin itself. Fixes #36.
=> Fix ComposeNaming rule being applied to operators

core-detekt/src/test/kotlin/io/nlopez/rules/core/detekt/DetektComposeKtConfigTest.kt, gradle/libs.versions.toml
Updates detekt to 1.23.0, and fixes the Detekt config test that failed due to a new deprecation.
=> Update detekt to 1.23.0

build.gradle
Update the spotless configuration to use the same ktlint version as the one being used in the rest of the project.
=> Use spotless with ktlint 0.49.1

rules/common/src/main/kotlin/io/nlopez/compose/rules/ComposeParameterOrder.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ComposeParameterOrderCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ComposeParameterOrderCheckTest.kt
=> Allow nullable types for trailing lambdas in ComposeParameterOrder

docs/detekt.md, docs/ktlint.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/ComposePreviewPublic.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ComposePreviewPublicCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ComposePreviewPublicCheck.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/EditorConfigProperties.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ComposePreviewPublicCheckTest.kt
Make it so all public composables that are previews are disallowed. Private and internal methods are good to go.
For a bit of context, historically this was gated so that if the public param had a PreviewParameter annotation, we would be sure it's for sure only used for previews, as the Twitter for Android codebase (which was its original test bed) had a bunch of preview composables on public methods, and I just wanted to get out of the way there. But they shouldn't really be public if they are annotated, even if this causes duplication -- just a matter of addressing possible future footguns: if they are really public, it means they can be consumed from other gradle modules, which means it's a public facing API, which means it should NOT be exposing a preview.
Fixes #24, although …
=> Report all non-public composables unconditionally

core-common/src/main/kotlin/io/nlopez/rules/core/util/Composables.kt, docs/detekt.md, docs/rules.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/ComposeModifierNaming.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ComposeModifierNamingCheck.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ComposeRuleSetProvider.kt, rules/detekt/src/main/resources/config/config.yml, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ComposeModifierNamingCheckTest.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ComposeRuleSetProviderTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ComposeModifierNamingCheck.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ComposeRuleSetProvider.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ComposeModifierNamingCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ComposeRuleSetProviderTest.kt
As per the docs, `Modifier` parameters should either be called `modifier` in most cases, or in cases where there are modifiers for subcomponents, `${subcomponentName}Modifier`.
This rule makes sure this is enforced.
=> Add a rule to enforce correct naming of Modifier parameters

core-common/src/main/kotlin/io/nlopez/rules/core/util/KtFunctions.kt, docs/detekt.md, docs/rules.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/ComposeDefaultsVisibility.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ComposeDefaultsVisibilityCheck.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ComposeRuleSetProvider.kt, rules/detekt/src/main/resources/config/config.yml, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ComposeDefaultsVisibilityCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ComposeDefaultsVisibilityCheck.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ComposeRuleSetProvider.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ComposeDefaultsVisibilityCheckTest.kt
If a composable has an associated `Defaults` object to contain its default values, this object should have the same visibility as the composable itself. This will allow consumers to be able to interact or build upon the original intended defaults, as opposed to having to maintain their own set of defaults by copy-pasting.
=> Add rule to have ComponentDefaults objects matching the visibility of their composables

build.gradle, core-common/src/main/kotlin/io/nlopez/rules/core/util/Composables.kt, core-common/src/main/kotlin/io/nlopez/rules/core/util/KtDotQualifiedExpressions.kt, core-common/src/main/kotlin/io/nlopez/rules/core/util/Modifiers.kt, docs/detekt.md, docs/ktlint.md, docs/rules.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/ComposeModifierNotUsedAtRoot.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ComposeModifierReused.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ComposeModifierNotUsedAtRootCheck.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ComposeRuleSetProvider.kt, rules/detekt/src/main/resources/config/config.yml, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ComposeModifierMissingCheckTest.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ComposeModifierNotUsedAtRootCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ComposeModifierNotUsedAtRootCheck.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ComposeRuleSetProvider.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ComposeModifierMissingCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ComposeModifierNotUsedAtRootCheckTest.kt
Modifiers aim to modify the external behaviors and appearance of the component, so they must be applied to the top-most layout and be the first modifiers in the hierarchy. 
This patch makes it so by traversing from the usages of said modifiers, and going upwards in the composable hierarchy to see if there is any other content emitter (by leveraging the already existing code for this).
=> Add rule to ensure modifiers are used at the top-most composable

core-common/src/main/kotlin/io/nlopez/rules/core/util/Composables.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ComposeModifierNotUsedAtRootCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ComposeModifierNotUsedAtRootCheckTest.kt
The `KtCallExpression.emitsContent` method was returning false positives after the change to check for Modifier usages, due to it not filtering out the types of expressions where a chained `Modifier` would be useful (e.g. only in `KtDotQualifiedExpression`, really). 
This patch makes it so that the fallback for the `valueArguments` check in `emitsContent` only looks into things like `Modifier.fillMaxWidth().whatever(...)` and the like: basically `KtDotQualifiedExpression`s with the root of `Modifier`.
Fixes #84
=> Fix emitsContent checking KtLambdaExpressions for Modifier usages

build.gradle, gradle/libs.versions.toml, rules/common/src/main/kotlin/io/nlopez/compose/rules/ComposePreviewPublic.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ComposeViewModelInjection.kt
Due to the reasons exposed in https://github.com/pinterest/ktlint/pull/2044/, this is not trivial - we need to rewrite the fixes manually or remove them altogether. Not being able to rely on the embedded kotlin compiler plugin for this is less than ideal, I wanted to stay away from ASTNode as much as possible :(
TODO:
=> Update ktlint to 1.0.0

docs/detekt.md, docs/ktlint.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/ComposeViewModelForwarding.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ComposeViewModelForwardingCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ComposeViewModelForwardingCheck.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/EditorConfigProperties.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ComposeViewModelForwardingCheckTest.kt
Currently, only classes ending in "ViewModel" were subject to the forwarding rule. This type of check should apply to any state holder, and if you use things other than ViewModels (e.g. presenters, or whatever other type of component I wouldn't think of), this rule now allows you to configure it if you want. It will default to look for types ending in "ViewModel" and "Presenter" but allow further configurations.
=> Allow configuration of state holder classes

core-common/src/main/kotlin/io/nlopez/rules/core/util/Previews.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ComposeModifierMissingCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ComposeModifierMissingCheckTest.kt
The `@Preview` annotation in a multipreview could be at the beginning. 
Should fix #98 ?
=> Update @Preview annotation detection

README.md, docs/index.md
Adds a migration guide for people coming from https://github.com/twitter/compose-rules/issues/112#issuecomment-1406286334
(and Hey Nacho 👋 😆)
=> Add migration guide to README.md

mkdocs.yml
After reading it in a mkdocs project issue, I found that the https://pypi.org/project/mdx-truly-sane-lists/ extension is supposed to help with mkdocs messing up lists. Let's give it a try.
=> Try fixing mkdocs borked lists

build.gradle, core-common/src/main/kotlin/io/nlopez/rules/core/util/Modifiers.kt, docs/detekt.md, docs/rules.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/ComposeModifierClickableOrder.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ComposeModifierNotUsedAtRoot.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ComposeModifierClickableOrderCheck.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ComposeRuleSetProvider.kt, rules/detekt/src/main/resources/config/config.yml, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ComposeModifierClickableOrderCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ComposeModifierClickableOrderCheck.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ComposeRuleSetProvider.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ComposeModifierClickableOrderCheckTest.kt
Add a new rule that detects a suspicious chain of modifiers, e.g. using clipping / background with shapes after a clickable-like modifier will likely result in incorrect UI.
Fixes #90
=> Add ModifierClickableOrder rule

rules/common/src/main/kotlin/io/nlopez/compose/rules/ComposeModifierNaming.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ComposeModifierNamingCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ComposeModifierNamingCheckTest.kt
The value of this PR depends on how strict you'd prefer the rule but the PR addresses the Compose Modifier naming rule not currently catching the following cases:
- Composable function with single modifier not named "modifier" but ends with "Modifier":
```
@Composable
fun Something1(myModifier: Modifier) {}
```
- Composable function non-initial modifier named exactly "modifier"
```
@Composable
fun Something1(myModifier: Modifier, modifier: Modifier) {}
```
=> Update compose modifier naming rule

docs/rules.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/ComposeModifierComposable.kt
Using `composed` for Modifiers is not the recommended practice anymore. Instead, `Modifier.Node` should be used. This commit updates the docs to reflect that.
Fixes #118
=> Fix documentation about composed modifiers

docs/detekt.md, docs/rules.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/ComposableAnnotationNaming.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ComposableAnnotationNamingCheck.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ComposeRuleSetProvider.kt, rules/detekt/src/main/resources/config/config.yml, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ComposableAnnotationNamingCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ComposableAnnotationNamingCheck.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ComposeRuleSetProvider.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ComposableAnnotationNamingCheckTest.kt
Adds a new rule to make sure all @ComposableTargetMarker annotated annotations (e.g. custom composable annotations) end with `Composable`.
=> Add ComposableAnnotationNaming rule

docs/detekt.md, docs/rules.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/CompositionLocalNaming.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ComposeRuleSetProvider.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/CompositionLocalNamingCheck.kt, rules/detekt/src/main/resources/config/config.yml, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/CompositionLocalNamingCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ComposeRuleSetProvider.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/CompositionLocalNamingCheck.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/CompositionLocalNamingCheckTest.kt
Initially, this rule was removed in be4ea6fbed61abfef0db68a7ee2f5458ae2b8ca4 because Android lint has a similar rule already. However, having it as part of this ruleset is useful for KMP projects anyway.
=> Bring back CompositionLocalNaming check

rules/common/src/main/kotlin/io/nlopez/compose/rules/MultipleContentEmitters.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/MultipleContentEmittersCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/MultipleContentEmittersCheckTest.kt
Detect for loops (in a best effort way) and have them influence calculations on MultipleContentEmitters, so that we can detect more issues of this ilk.
=> Take for loops into account for MultipleContentEmitters rule

core-common/src/main/kotlin/io/nlopez/rules/core/ComposeKtConfig.kt, core-common/src/main/kotlin/io/nlopez/rules/core/ComposeKtVisitor.kt, core-common/src/main/kotlin/io/nlopez/rules/core/util/Composables.kt, core-detekt/src/main/kotlin/io/nlopez/rules/core/detekt/DetektRule.kt, core-ktlint/src/main/kotlin/io/nlopez/rules/core/ktlint/KtlintRule.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ComposableAnnotationNaming.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/CompositionLocalAllowlist.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/CompositionLocalNaming.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ContentEmitterReturningValues.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/DefaultsVisibility.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierClickableOrder.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierComposable.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierMissing.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierNaming.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierNotUsedAtRoot.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierReused.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierWithoutDefault.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/MultipleContentEmitters.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/MutableParameters.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/Naming.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ParameterOrder.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/PreviewAnnotationNaming.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/PreviewPublic.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/RememberContentMissing.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/RememberStateMissing.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/UnstableCollections.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ViewModelForwarding.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ViewModelInjection.kt
As there are a couple issues with config setting (#109, #142), I want to eliminate a potential (?) source of issues, which is using the UserData dictionaries that are present in PSIElement, and use the config wrappers directly. This should be a more robust solution in theory, and removes somewhere to look at when something's wrong, which is great. 
The annoying part which was being able to use the config in content emitter checks can be worked around by using context receivers easily, so I did that.
=> Update config setting to avoid PsiElement#get/putUserData

core-common/src/main/kotlin/io/nlopez/rules/core/util/KtCallableDeclarations.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/RememberStateMissing.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/RememberStateMissingCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/RememberStateMissingCheckTest.kt
Adds support for `mutableIntStateOf`, `mutableFloatStateOf`, `mutableDoubleStateOf` and `mutableLongStateOf` in RememberStateMissing rule.
=> Add support for numeric state types in RememberStateMissing

core-common/src/main/kotlin/io/nlopez/rules/core/util/KtCallableDeclarations.kt, docs/detekt.md, docs/rules.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/MutableStateParameter.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ComposeRuleSetProvider.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/MutableStateParameterCheck.kt, rules/detekt/src/main/resources/config/config.yml, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/MutableStateParameterCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ComposeRuleSetProvider.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/MutableStateParameterCheck.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/MutableStateParameterCheckTest.kt
This commit introduces a new rule, `MutableStateParameter`, which has spawned from `MutableParameters`. It basically takes out the `MutableState` check to a separate rule, mostly to provide a better explanation about why is it a bad idea to use such classes in the signature of a composable function.
Fixes #133.
=> Take out MutableStateParameter rule from MutableParameters rule

core-common/src/main/kotlin/io/nlopez/rules/core/util/Modifiers.kt, docs/detekt.md, docs/ktlint.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierComposable.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierMissing.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierNaming.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierNotUsedAtRoot.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierReused.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierWithoutDefault.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ParameterOrder.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ModifierMissingCheckTest.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ParameterOrderCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/EditorConfigProperties.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ModifierComposableCheck.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ModifierMissingCheck.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ModifierNamingCheck.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ModifierNotUsedAtRootCheck.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ModifierReusedCheck.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ModifierWithoutDefaultCheck.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ModifierMissingCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ParameterOrderCheckTest.kt
Adds the ability to configure custom modifier types. By default, `Modifier` and `GlanceModifier` types are considered modifiers, but some libraries might want to include their own modifier types so it makes sense to open the door to configurability there.
Addresses #141 (at least its last remaining concern).
=> Add support to configure custom Modifier types

docs/detekt.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierClickableOrder.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierNotUsedAtRoot.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ModifierClickableOrderCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ModifierClickableOrderCheck.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ModifierClickableOrderCheckTest.kt
`ModifierClickableOrder` was only looking into `modifier` named parameters. However this rule could be applied to any type of modifier, so if more than one modifier is used, this PR will make it so it catches those issues as well.
=> Allow ModifierClickableOrder rule to look into multiple modifiers

.github/workflows/update-release.yaml
Let's include the normal jars in the release as well, as they are the ones that are uploaded to maven central anyway.
=> Update ci to also include normal build jars

core-common/src/main/kotlin/io/nlopez/rules/core/util/Composables.kt, docs/detekt.md, docs/ktlint.md, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/MultipleContentEmittersCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/EditorConfigProperties.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/MultipleContentEmittersCheck.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/MultipleContentEmittersCheckTest.kt
Adds the ability to configure composables that probably emit content that we don't want to count towards the count for emissions. This is useful, for example, for composables that wrap stuff that will render in another window (like a Dialog or a Modal), which they do indeed emit content but we might not want to take it into account because it's not a mistake that is used at the same level as other stuff (e.g. a Scaffold composable).
Closes #166.
=> Add denylist for content emitters

core-common/src/main/kotlin/io/nlopez/rules/core/util/Composables.kt, docs/detekt.md, docs/ktlint.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/ContentEmitterReturningValues.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/MultipleContentEmitters.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/MultipleContentEmittersCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/EditorConfigProperties.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/MultipleContentEmittersCheck.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/MultipleContentEmittersCheckTest.kt
Refactor to push up the layers the direct/indirect count emitters. It simplifies the MultipleEmitters and ContentEmitterReturningValues rules, as they had a lot of shared code.
=> Extract emission to count code to Composables.kt

core-common/src/main/kotlin/io/nlopez/rules/core/util/KotlinUtils.kt, docs/detekt.md, docs/ktlint.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/ViewModelForwarding.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ViewModelForwardingCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/EditorConfigProperties.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ViewModelForwardingCheck.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ViewModelForwardingCheckTest.kt
Creates a new configuration value `allowedForwarding` which will act as an allowlist for composable function names that allow VM forwarding. This is specially useful for Compose MP, where we don't typically have factory functions to acquire VMs, and we might have different requirements for the different platforms (e.g. Android with stuff in a Scaffold, iOS with stuff that is wrapped by native SwiftUI views).
Closes #165.
=> Add allowlist of composable names to VMForwarding rule

docs/detekt.md, docs/ktlint.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/ParameterOrder.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ParameterOrderCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/EditorConfigProperties.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ParameterOrderCheck.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ParameterOrderCheckTest.kt
Adds `treatAsLambda` as a configuration parameter for the ParameterOrder rule. This allows any arbitrary type to be treated as a lambda, aka not being flagged when not having a default value when being last in a method signature (like what we do for functional types already).
Partially addresses #153.
=> Add treatAsLambda to ParamOrder rule configuration

rules/common/src/main/kotlin/io/nlopez/compose/rules/ParameterOrder.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ParameterOrderCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ParameterOrderCheckTest.kt
With this change we can automatically infer lambdas from typealiases and functional interfaces that are in the same file as the composable (without type resolution this is as good as it gets). This will alleviate the need to add manually all of those to the configuration, which is surely going to make things easier.
Closes #153.
=> Infer lambdas from typealias/fun interfaces in ParameterOrder

rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierClickableOrder.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ModifierClickableOrderCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ModifierClickableOrderCheckTest.kt
Made `ModifierClickableOrder` rule useful for more cases: if the shape is referenced via MaterialTheme.shapes or similar, or if clip is used at all (before I was checking for shape params or shape classes, but clip only takes a shape so anything goes).
=> Add more supported cases to ModifierClickableOrder

core-common/src/main/kotlin/io/nlopez/rules/core/util/Lambdas.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ParameterOrder.kt
Want to use this for another rule, so moving this first to a reusable place.
=> Move lambda detection code to a common util module

core-common/src/main/kotlin/io/nlopez/rules/core/util/KotlinUtils.kt, docs/detekt.md, docs/rules.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/LambdaParameterInRestartableEffect.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ComposeRuleSetProvider.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/LambdaParameterInRestartableEffectCheck.kt, rules/detekt/src/main/resources/config/config.yml, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/LambdaParameterInRestartableEffectCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ComposeRuleSetProvider.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/LambdaParameterInRestartableEffectCheck.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/LambdaParameterInRestartableEffectCheckTest.kt
Adds a rule to detect potential troubling scenarios where a lambda parameter in a composable is used directly in a restartable effect (e.g. LaunchedEffect/DisposableEffect), without using `rememberUpdatedState` or using the param as a key to the effect.
This currently bit me in the ass at work, so adding a basic rule for just lambdas (for now) to tackle this.
=> Add LambdaParameterInRestartableEffect rule

core-common/src/main/kotlin/io/nlopez/rules/core/util/Composables.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/MultipleContentEmittersCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/MultipleContentEmittersCheckTest.kt
Allows for code similar to this to be counted towards emissions at the top level. 
```kotlin
@Composable
fun A(title: String?, subtitle: String?) {
title?.let { Text(it) }
subtitle?.let { Text(it) }
}
```
Fixes #191
=> Add safe accessors + let to the content emission counters

core-common/src/main/kotlin/io/nlopez/rules/core/util/Composables.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ViewModelInjection.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ViewModelInjectionCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ViewModelInjectionCheckTest.kt
Filters out the rule violation candidates if they are used inside of a androidx.navigation DSL (NavHost/composable), as it'd be legit using them there. It also removes the autofix capability when the VM factories have arguments, as it's just not practical to check where all the params would come from (and if they'd be available in the composable params).
Fixes #212
=> Fix false positives with vm-injection rule when in android.navigation DSL

docs/detekt.md, docs/rules.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierComposed.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ComposeRuleSetProvider.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ModifierComposedCheck.kt, rules/detekt/src/main/resources/config/config.yml, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ModifierComposedCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ComposeRuleSetProvider.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ModifierComposedCheck.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ModifierComposedCheckTest.kt
Adds a `ModifierComposed` rule, to detect all usages of `composed` in Modifiers and direct people to use `Modifier.Node` instead, as it's more performant and the recommended option nowadays.
Closes #203
=> Add ModifierComposed rule

.github/workflows/build.yaml
closeAndReleaseRepository was deprecated: https://github.com/vanniktech/gradle-maven-publish-plugin/releases/tag/0.28.0
=> Use releaseRepository

rules/common/src/main/kotlin/io/nlopez/compose/rules/ViewModelForwarding.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ViewModelForwardingCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ViewModelForwardingCheckTest.kt
This covers the case of forwarding within scope functions, addressing #117.
=> Check for Scope Functions in ViewModel Forwarding Rule

core-common/src/main/kotlin/io/nlopez/rules/core/util/KotlinUtils.kt, core-common/src/main/kotlin/io/nlopez/rules/core/util/KtDotQualifiedExpressions.kt, core-common/src/main/kotlin/io/nlopez/rules/core/util/PsiElements.kt, docs/detekt.md, docs/ktlint.md, docs/rules.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/Material2.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ComposeRuleSetProvider.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/Material2Check.kt, rules/detekt/src/main/resources/config/config.yml, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/Material2CheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ComposeRuleSetProvider.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/EditorConfigProperties.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/Material2Check.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/Material2CheckTest.kt
Add a new rule (opt-in) to detect Material 2 usages. This has bit me in the ass at work, so I have a vested interest it goes in 🤣 
It will detect usages of the material 2 apis in imports and as fqns in the code. It also has support for an allowlist of apis, based on their package hierarchy.
=> Add opt-in rule for disallowing Material2 APIs

core-common/src/main/kotlin/io/nlopez/rules/core/util/KotlinUtils.kt, core-common/src/main/kotlin/io/nlopez/rules/core/util/KtConstantExpressions.kt, docs/detekt.md, docs/rules.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/MutableStateAutoboxing.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ComposeRuleSetProvider.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/MutableStateAutoboxingCheck.kt, rules/detekt/src/main/resources/config/config.yml, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/MutableStateAutoboxingCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ComposeRuleSetProvider.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/MutableStateAutoboxingCheck.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/MutableStateAutoboxingCheckTest.kt
`mutableIntStateOf`, `mutableLongStateOf`, `mutableDoubleStateOf`, `mutableFloatStateOf` are essentially counterparts to `mutableStateOf`, but with the added advantage of circumventing autoboxing on JVM platforms. This distinction renders them more memory efficient, making them the preferable choice when dealing with primitive types such as double, float, int, and long.
There is an official lint rule already for this, but lint won't help with KMP projects like the one I work on at my day job, so detecting this is useful anyway.
=> Add rule to use the non-autoboxing versions of mutableStateOf when possible

core-common/src/main/kotlin/io/nlopez/rules/core/util/Composables.kt
Adds to the list of known content emitters some of the M3 specific ones.
=> Add M3 composables to the list of known content emitters

core-common/src/main/kotlin/io/nlopez/rules/core/util/KotlinUtils.kt, docs/detekt.md, docs/ktlint.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/ViewModelForwarding.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ViewModelForwardingCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/EditorConfigProperties.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ViewModelForwardingCheck.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ViewModelForwardingCheckTest.kt
Adds a new param to be able to exempt the given patterns from the ViewModelForwarding rule.
Fixes #235
=> Add an allowlist for VM names for whose ViewModelForwarding is allowed

core-common/src/main/kotlin/io/nlopez/rules/core/util/Modifiers.kt, core-common/src/main/kotlin/io/nlopez/rules/core/util/PsiElements.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierClickableOrder.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierNotUsedAtRoot.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierReused.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ModifierReusedCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ModifierReusedCheckTest.kt
Detects whether modifier parameters are being shadowed by another function's parameters.
Fixes #236
=> Detect shadowing of modifier names in ModifierReused

core-common/src/main/kotlin/io/nlopez/rules/core/util/Composables.kt, core-common/src/main/kotlin/io/nlopez/rules/core/util/PsiElements.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierNotUsedAtRoot.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ModifierNotUsedAtRootCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ModifierNotUsedAtRootCheck.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ModifierNotUsedAtRootCheckTest.kt
Make ModifierNotUsedAtRoot to honor contentEmittersDenylist, so if any non-content emitter (whether default one or provided by config) is in the parent hierarchy of the composable, the rule gets ignored.
Fixes #240
=> Make ModifierNotUsedAtRoot honor contentEmittersDenylist

rules/common/src/main/kotlin/io/nlopez/compose/rules/MutableStateAutoboxing.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/MutableStateAutoboxingCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/MutableStateAutoboxingCheckTest.kt
Adds a bunch of more detectors for Lists/Sets/Maps of numeric primitives. TBH it's not very worth pursuing more coverage here, as it's trivial with type resolution but super annoying when done manually, so I guess it'll be left as it is for now.
=> Add more autoboxing detections

core-common/src/main/kotlin/io/nlopez/rules/core/util/Lambdas.kt, docs/detekt.md, docs/ktlint.md, docs/rules.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/ContentTrailingLambda.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ComposeRuleSetProvider.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ContentTrailingLambdaCheck.kt, rules/detekt/src/main/resources/config/config.yml, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ContentTrailingLambdaCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ComposeRuleSetProvider.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ContentTrailingLambdaCheck.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/EditorConfigProperties.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ContentTrailingLambdaCheckTest.kt
Adds a new rule so that the `content` composable is the trailing lambda. This one is less restrictive than the one in the official lints (where anything with "content" in it could be asked to be trailing, even if things like `titleContent` might not make much sense).
=> Add ContentTrailingLambda rule to ensure content slot is trailing

docs/detekt.md, docs/ktlint.md, docs/rules.md, rules/detekt/src/main/resources/config/config.yml, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/EditorConfigProperties.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/UnstableCollectionsCheck.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/UnstableCollectionsCheckTest.kt
Compose is enabling soon strong skipping by defualt, which will make this rule unuseful. 
I'm updating it to be opt-in, so it won't be an issue if people keep their current configs, while new users will be able to choose while having a sensible default.
Closes #251
=> Make UnstableCollections rule opt-in

docs/detekt.md, docs/rules.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/ParameterNaming.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ComposeRuleSetProvider.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ParameterNamingCheck.kt, rules/detekt/src/main/resources/config/config.yml, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ParameterNamingCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ComposeRuleSetProvider.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ParameterNamingCheck.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ParameterNamingCheckTest.kt
Adds a new rule to ensure lambda parameters on composables that send events (e.g. start with `on`) are in present tense.
Fixes #266
=> Add ParameterNaming rule

docs/ktlint.md
Improvementes:
* The ktlint-intellij-plugin is now longer label as 'unofficial' as it is now maintained by same maintainer as ktlint.
* Added configuration to avoid conflicts with ktlint's `standard:function-naming` rule
=> Improve documentation for ktlint rules

docs/rules.md
Unless i'm missing something, the `.editorconfig` property name is incorrect. The correct property name can be found in the homepage.
=> Fixed incorrect property name for CompositionLocal allow list.

rules/common/src/main/kotlin/io/nlopez/compose/core/util/Composables.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/MultipleContentEmittersCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/MultipleContentEmittersCheckTest.kt
Improves the basics behind the content emitter counts, and makes it more flexible and easier to update. 
I've also added  support for branching code (e.g. if/else), so that if any of the branches contains emitters, they are taken into account.
=> Improve content emitter logic and support for conditional emitter count

docs/detekt.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/ParameterNaming.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ParameterNamingCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ParameterNamingCheck.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ParameterNamingCheckTest.kt
I just noticed I used the wrong parameter when updating this rule. This introduces a breaking change though, but it's good... as it will spare us from future issues.
ParameterNaming lambdas shouldn't be just composable lambdas, but all lambdas instead.
=> Update ParameterNaming to use treatAsLambda instead of treatAsComposableLambda

rules/common/src/main/kotlin/io/nlopez/compose/core/util/Composables.kt, rules/common/src/main/kotlin/io/nlopez/compose/core/util/KotlinUtils.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ViewModelForwarding.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/MultipleContentEmittersCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/MultipleContentEmittersCheckTest.kt
Adds support for elvis operator operations when finding content emitters, and also adds direct support for scoped operations as well - not only for safe accessors this time (so anything wrapped with a with, run, etc would also be found).
=> Add binary expressions support to MultipleContentEmitters

rules/common/src/main/kotlin/io/nlopez/compose/core/util/Composables.kt
We only wanted this supported for elvis operators anyway, let's keep away the weirdness in assignments and other stuff that would fall in KtBinaryOperator.
=> Restrict emitters count for KtBinaryExpression to ELVIS only

rules/common/src/main/kotlin/io/nlopez/compose/core/util/Composables.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/MultipleContentEmittersCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/MultipleContentEmittersCheckTest.kt
Now it supports `when` statements, plus more forms of loops (`while`, `do ... while`, and the former `for`).
=> Add support to when statements while counting emitters

rules/common/src/main/kotlin/io/nlopez/compose/core/util/Composables.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/MultipleContentEmittersCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/MultipleContentEmittersCheckTest.kt
Early returns were the Achilles heel of the content emitter count algorithm. I've updated it to be able to at least detect the issues that would make it fail detection, even if the count is not going to be accurate, at least the 0 vs 1 calculations would be. Let's see how it holds up.
Fixes #308
=> Detect early returns in content emitter count

rules/common/src/main/kotlin/io/nlopez/compose/core/util/Composables.kt, rules/common/src/main/kotlin/io/nlopez/compose/core/util/PsiElements.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ModifierMissingCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ModifierMissingCheck.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ModifierReusedCheck.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ModifierMissingCheckTest.kt
Simplified the detection of potential content emitters in functions, with a slight behavior change:
Before, no children would be considered if the parents were any of these set of hardcoded composables:
```
setOf(
"AlertDialog",
"DatePickerDialog",
"Dialog",
"ModalBottomSheetLayout",
"ModalBottomSheet",
"Popup",
)
```
Now, no children will be considered if the parents were any of these hardcoded composables, plus any of the composables defined in `contentEmittersDenylist` in the rules configuration. That way, you can get rid of false positives that might have originated with your own foundational composables.
=> Stop content emitter detection also by contentEmittersDenylist

rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierMissing.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierWithoutDefault.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ModifierMissingCheckTest.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ModifierWithoutDefaultCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ModifierMissingCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ModifierWithoutDefaultCheckTest.kt
Add special cases to ignore some of the Modifier adjacent rules (ModifierMissing, ModifierWithoutDefault) if the composable function is an extension function for Modifier (aka a Modifier factory function, which is now less frowned upon).
=> Ignore modifier factory functions in ModifierMissing/ModifierWithoutDefault

build.gradle.kts, rules/common/src/main/kotlin/io/nlopez/compose/core/util/Composables.kt, rules/common/src/main/kotlin/io/nlopez/compose/core/util/Lambdas.kt, rules/common/src/main/kotlin/io/nlopez/compose/core/util/Modifiers.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ContentEmitterReturningValues.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ContentTrailingLambda.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/LambdaParameterInRestartableEffect.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierClickableOrder.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierComposable.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierComposed.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierMissing.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierNaming.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierNotUsedAtRoot.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierReused.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierWithoutDefault.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/MultipleContentEmitters.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ParameterNaming.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ParameterOrder.kt
Kotlin 2.0.20 warns about context receiver deprecation, so let's get rid of them preemptively 😢 
This makes me so sad, because I liked context receivers. At some point in the future we'll get context parameters (which look like a good replacement for the usages I typically gave context receivers) but there's going to be a time in between context receivers are deprecated and context params are available, so I'm gonna go the boring route and turn them all into function params :sigh:
=> Remove context receivers

docs/detekt.md, docs/ktlint.md, rules/common/src/main/kotlin/io/nlopez/compose/core/util/KtAnnotateds.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierMissing.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/DetektRule.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ModifierMissingCheck.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ModifierMissingCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/KtlintRule.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/EditorConfigProperties.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ModifierMissingCheck.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ModifierMissingCheckTest.kt
Added a way to suppress the execution of `ModifierMissing` rule based on annotations.
In theory, it looks like Detekt should have done this automatically but for some reason it wasn't happening for me in tests, so I added it manually. If it works and I did something wrong... no harm in the extra checking I guess 🤷 So, for detekt, the classic suppression style should work:
```yaml
ModifierMissing:
active: true
ignoreAnnotated: ['Potato', 'Banana']
```
On ktlint there's no such thing, plus the rules are shared so we need to make them specific. So, you'd need to use `compose_modifier_missing_ignore_annotated` in your .editorconfig 
```
compose_modifier_missing_ignore_annotated = Potato,Banana
```
Fixes #318
=> Add ignoreAnnotated/compose_modifier_missing_ignore_annotated to ModifierMissing

docs/detekt.md, docs/rules.md, rules/common/src/main/kotlin/io/nlopez/compose/core/util/Lambdas.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/LambdaParameterEventTrailing.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ComposeRuleSetProvider.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/LambdaParameterEventTrailingCheck.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/LambdaParameterEventTrailingCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ComposeRuleSetProvider.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/LambdaParameterEventTrailingCheck.kt
Adds a new rule to detect, whenever possible, event lambdas as trailing parameters in a `@Composable` that emits content.
Closes #330
=> Add LambdaParameterEventTrailing rule

docs/detekt.md, docs/rules.md, rules/common/src/main/kotlin/io/nlopez/compose/core/util/KotlinUtils.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ContentSlotReused.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ComposeRuleSetProvider.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ContentSlotReusedCheck.kt, rules/detekt/src/main/resources/config/config.yml, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ContentSlotReusedCheckTest.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ContentTrailingLambdaCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ComposeRuleSetProvider.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ContentSlotReusedCheck.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ContentSlotReusedCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ContentTrailingLambdaCheckTest.kt
Adds a detector for slots being used in different branches of a composable function. 
Idea to do this came from https://github.com/slackhq/compose-lints/issues/367 😄
=> Add ContentSlotReused rule

rules/common/src/main/kotlin/io/nlopez/compose/core/util/KtCallableDeclarations.kt, rules/common/src/main/kotlin/io/nlopez/compose/core/util/KtParameters.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/ContentSlotReused.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ContentSlotReusedCheck.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ContentSlotReusedCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ContentSlotReusedCheckTest.kt
This PR includes a bunch of simplification and improvements over the original code, plus a bunch of other tests cases to pass. The most notable is that now it supports nullable slots properly as well.
=> Add support to nullable slots in ContentSlotReused

docs/detekt.md, docs/ktlint.md, docs/rules.md, rules/common/src/main/kotlin/io/nlopez/compose/core/util/Previews.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/PreviewNaming.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ComposeRuleSetProvider.kt, rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/PreviewNamingCheck.kt, rules/detekt/src/main/resources/config/config.yml, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/PreviewNamingCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ComposeRuleSetProvider.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/EditorConfigProperties.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/PreviewNamingCheck.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/PreviewNamingCheckTest.kt
Adds an opt-in rule to be able to enforce a naming rule on preview composable functions. It allows users to be able to add `Preview` as suffix, prefix or ensure that's anywhere in the text. It also contains an autofix that adds it for you. As preview composables shouldn't be called by anybody else in your codebase, it should be fine (and if they are called, make better choices lol)
Closes #229
=> Add PreviewNaming opt-in rule

rules/common/src/main/kotlin/io/nlopez/compose/core/util/Lambdas.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ContentSlotReusedCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ContentSlotReusedCheckTest.kt
`isComposableLambda` logic was flawed when dealing with nullable types. It was basically letting any lambda to return true (regardless of it actually being composable). I've fixed it and added unit tests around cases that would make it trip.
Fixes #346
=> Fix KtTypeReference#isComposableLambda

gradle/libs.versions.toml, rules/common/src/main/kotlin/io/nlopez/compose/core/ComposeKtVisitor.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/Material2.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/PreviewNaming.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/UnstableCollections.kt, rules/detekt/build.gradle.kts, rules/detekt/src/main/resources/config/config.yml, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ComposeRuleSetProviderTest.kt
There have been some issues with either forgetting to add stuff to the detekt default config, or screwing up the `active` values (whether they are opt-in or not by default).
I've added a test to prevent this from happening again, which will parse the yaml file and assert that all rules are added to it, and that the active value is correct.
=> Add test to make sure the detekt default config is correct

gradle/libs.versions.toml, rules/detekt/build.gradle.kts, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ComposeRuleSetProviderTest.kt, rules/ktlint/build.gradle.kts, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ComposeRuleSetProviderTest.kt
This is to make sure external contributors don't forget to add the detekt/ktlint version of the rules (I've had some instances of this, people typically forget to include the ktlint version), and that all rules in both detekt/ktlint have unit tests. 
This would make working in this repo more straightforward, as tools would yell at you if you forget something. It's a lot, and it's getting hard to track, I know 😆
=> Add tests to make sure rules have tests

docs/detekt.md, docs/ktlint.md
Adds the supported version of ktlint/detekt in their respective section on the docs. This is interesting for things like choosing a version that fits your needs, specially in stuff like IDE plugins where versions sort of need to match to avoid issues.
Closes #361
=> Add version grid support in ktlint/detekt part of the docs

rules/common/src/main/kotlin/io/nlopez/compose/core/util/KtCallableDeclarations.kt, rules/common/src/main/kotlin/io/nlopez/compose/core/util/Lambdas.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ContentSlotReusedCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ContentSlotReusedCheckTest.kt
Composables that don't return Unit shouldn't be counted as emitting content. `contentSlots` helper will filter them out now, which in turn fixes some `ContentSlotReused` false positives.
Fixes #376
=> Ignore lambdas that dont return Unit in ContentSlotReused

rules/detekt/src/main/resources/config/config.yml, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ComposeRuleSetProviderTest.kt
Added a test to verify that all rules in the default config.yml file are listed in alphabetical order and match the available rules in the ruleset. Reordered `RememberMissing` and `RememberContentMissing` entries to maintain alphabetical order.
=> Add test to ensure config.yml file entries are sorted

gradle/libs.versions.toml
Should fix #396.
Moving back ktlint as well so I can do a release, before bumping it again.
=> Revert Kotlin to 2.0.21

build.gradle.kts, rules/common/build.gradle.kts, rules/detekt/build.gradle.kts, rules/ktlint/build.gradle.kts
After upgrading kotlin version to `2.1.0` kotlin gradle plugin raises warning if `kotlin-compiler-embeddable` is present in the classpath:
```
w: The artifact `org.jetbrains.kotlin:kotlin-compiler-embeddable` is present in the build classpath along Kotlin Gradle plugin.
This may lead to unpredictable and inconsistent behavior.
For more details, see: https://kotl.in/gradle/internal-compiler-symbols
```
According to the output of `buildEnvironment` Gradle task compose-rules add kotlin-compiler-embeddable to the classpath:
```
\--- io.nlopez.compose.rules:ktlint:0.4.22
+--- com.pinterest.ktlint:ktlint-rule-engine:1.4.1
|    +--- com.pinterest.ktlint:ktlint-logger:1.4.1
|    |    +--- dev.drewhamilton.poko:poko-annotations:0.17.2
|    |    |    \--- …
```
=> kotlin-compiler-embeddable dependencies should be compileOnly

docs/detekt.md, docs/ktlint.md, rules/common/src/main/kotlin/io/nlopez/compose/rules/ParameterNaming.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ParameterNamingCheckTest.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/EditorConfigProperties.kt, rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ParameterNamingCheck.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ParameterNamingCheckTest.kt
Compose contains too many names that use past verbs, so I decided to allow these names.
Maybe it's worth renaming the new field; I'm open to suggestions :)
=> Providing list of allowed Lambda Names for ParameterNaming

rules/common/src/main/kotlin/io/nlopez/compose/core/util/Composables.kt, rules/common/src/main/kotlin/io/nlopez/compose/rules/LambdaParameterInRestartableEffect.kt, rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/LambdaParameterInRestartableEffectCheckTest.kt, rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/LambdaParameterInRestartableEffectCheckTest.kt
Add some specific exemptions for restartable effects and vm forwarding for the androidx.lifecycle.compose effects (and their scope functions).
=> Add exemptions for androidx.lifecycle.compose effects

.github/workflows/build.yaml, gradle/libs.versions.toml, rules/common-detekt/build.gradle.kts, rules/common-detekt/gradle.properties, rules/common-ktlint/build.gradle.kts, rules/common-ktlint/gradle.properties, rules/common/gradle.properties, rules/detekt/build.gradle.kts, rules/ktlint/build.gradle.kts, settings.gradle.kts
Vibe coding my way onto supporting different kotlin compiler versions in `:rules:detekt` and `:rules:ktlint`, mainly due to detekt being increasingly behind in their supported kotlin versions (and ktlint being fast, which kind of forces my hand to do some releases to support them better).
I want to be able to release versions, so something like this needs to happen. Sadly, my gradle-fu is rusty AF.
=> [WIP] Support separate kotlin compiler versions for detekt and ktlint
