- docs/rules.md
Fixes the documentation links for related rule classes.
> Fix github page rule links

- rules/common/src/main/kotlin/io/nlopez/compose/rules/ComposeContentEmitterReturningValues.kt
- rules/common/src/main/kotlin/io/nlopez/compose/rules/ComposeMultipleContentEmitters.kt
- rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ComposeMultipleContentEmittersCheckTest.kt
- rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ComposeMultipleContentEmittersCheckTest.kt
> Avoid running multiple emitter check with context receivers

- build.gradle
- gradle/libs.versions.toml
Bump ktlint version to the latest, 0.50.0. Can't be an automatic update due to spotlight not supporting it yet.
> Update ktlint to 0.50.0

- core-common/src/main/kotlin/io/nlopez/rules/core/util/Modifiers.kt
- rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierReused.kt
- rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ModifierReusedCheckTest.kt
- rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ModifierReusedCheckTest.kt
> Modifier reuse rule update - Check more than one modifier Param

- docs/ktlint.md
This support has been finished in https://github.com/diffplug/spotless/pull/1896.
> Update doc about the integration in Spotless

- .editorconfig
- build.gradle
- core-common/src/main/kotlin/io/nlopez/rules/core/util/ASTNodes.kt
- core-common/src/main/kotlin/io/nlopez/rules/core/util/KotlinUtils.kt
- core-common/src/main/kotlin/io/nlopez/rules/core/util/Modifiers.kt
- core-common/src/main/kotlin/io/nlopez/rules/core/util/PsiElements.kt
- core-detekt/src/main/kotlin/io/nlopez/rules/core/detekt/DetektComposeKtConfig.kt
- core-ktlint/src/main/kotlin/io/nlopez/rules/core/ktlint/KtlintComposeKtConfig.kt
- core-ktlint/src/test/kotlin/io/nlopez/rules/core/ktlint/KtlintComposeKtConfigTest.kt
- rules/common/src/main/kotlin/io/nlopez/compose/rules/DefaultsVisibility.kt
- rules/detekt/src/main/kotlin/io/nlopez/compose/rules/detekt/ComposeRuleSetProvider.kt
- rules/ktlint/src/main/kotlin/io/nlopez/compose/rules/ktlint/ComposeRuleSetProvider.kt
> Ktlint 1.0 styles

- rules/detekt/build.gradle
- rules/ktlint/build.gradle
> Add shadowJar relocation for kotlin embeddable

- docs/rules.md
> Fix link in documentation

- core-common/src/main/kotlin/io/nlopez/rules/core/util/KtAnnotateds.kt
- rules/common/src/main/kotlin/io/nlopez/compose/rules/Naming.kt
- rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/NamingCheckTest.kt
- rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/NamingCheckTest.kt
> Honor the ComposableNaming suppression in the Naming rule

- core-common/src/main/kotlin/io/nlopez/rules/core/util/KtCallExpressions.kt
- core-common/src/main/kotlin/io/nlopez/rules/core/util/Modifiers.kt
- rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierReused.kt
We'll probably be using the shadowing detection soon for other rules.
> Extract shadowing detection code to a helper fun

- core-common/src/main/kotlin/io/nlopez/rules/core/util/KtFunctions.kt
- rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierWithoutDefault.kt
- rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ModifierWithoutDefaultCheckTest.kt
- rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ModifierWithoutDefaultCheckTest.kt
> Add exception for open funs in ModifierWithoutDefault rule

- rules/common/src/main/kotlin/io/nlopez/compose/rules/LambdaParameterInRestartableEffect.kt
- rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/LambdaParameterInRestartableEffectCheckTest.kt
- rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/LambdaParameterInRestartableEffectCheckTest.kt
Composables which accept a parameter named `onDispose` will always raise a warning for its use in `DisposableEffect`, from the call to `DisposableEffectScope.onDispose`. This is a rare edge case but doesn't allow any workarounds other than renaming the lambda or suppressing.
To fix, I've implemented simple plain text matching to ignore any usages of `onDispose` in a `DisposableEffect`. This may not be perfect (as the TODO in test cases shows) but in the absence of type resolution it might be a reasonable workaround. Very open to more elegant solutions!
> Fix LambdaParameterInRestartableEffect conflict with `onDispose` lambda

- rules/common/src/main/kotlin/io/nlopez/compose/rules/ParameterOrder.kt
In some cases where the order is wrong, the suggested order might not be the best, so I'm gonna soften the message a little.
Addresses #268
> Update ParameterOrder messaging

- docs/rules.md
Let's make the ordering more clear in the writeup.
> Add example and diagram to param order docs

- rules/common/src/main/kotlin/io/nlopez/compose/rules/ParameterNaming.kt
- rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ParameterNamingCheckTest.kt
- rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ParameterNamingCheckTest.kt
> Add exceptions to present tenses finishing in -ed

- rules/common/src/main/kotlin/io/nlopez/compose/rules/ParameterNaming.kt
- rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ParameterNamingCheckTest.kt
- rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ParameterNamingCheckTest.kt
Addressing https://github.com/mrmans0n/compose-rules/issues/274#issuecomment-2137209612
> Add exception for onFocusChanged in ParameterNaming

- docs/rules.md
Update link to new domain of Chris' post.
> Update Chris website

- rules/common/src/main/kotlin/io/nlopez/compose/core/util/KtCallExpressions.kt
- rules/common/src/main/kotlin/io/nlopez/compose/rules/LambdaParameterInRestartableEffect.kt
- rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/LambdaParameterInRestartableEffectCheckTest.kt
- rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/LambdaParameterInRestartableEffectCheckTest.kt
> Add exemption for shadowed declarations on LambdaParameterInRestartableEffect

- rules/common/src/main/kotlin/io/nlopez/compose/rules/ModifierReused.kt
- rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ModifierReusedCheckTest.kt
- rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ModifierReusedCheckTest.kt
It was easy to trick ModifierReused for a false positive when using an early return. With these changes, that's harder now. I also had the chance to rewrite this part of the code to make it simpler to understand, and more robust -- so win/win I guess?
Added some unit tests as the cherry on top.
> Prevent false positives in ModifierReused due to early returns

- docs/rules.md
https://mrmans0n.github.io/compose-rules/rules/#ordering-composable-parameters-properly
> Attempt fixing nested list

- docs/rules.md
> Add explicit mention to the rule id in the docs

- mkdocs.yml
Add dark theme to take care of night owls.
> Added dark theme 

- scripts/create-rule.main.kts
Enhances the rule creation script to automatically update the detekt configuration file when creating new rules.
> Add new rules to config.yml automatically

- scripts/create-rule.main.kts
Going wild with the script, lol
> Add new rules alphabetically in create-rule script

- rules/common/src/main/kotlin/io/nlopez/compose/rules/ParameterNaming.kt
> Exclude "Left" from the list for ParameterNaming

- rules/common/src/main/kotlin/io/nlopez/compose/rules/ParameterNaming.kt
- rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ParameterNamingCheckTest.kt
- rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ParameterNamingCheckTest.kt
See [`Modifier.onPlaced`](https://developer.android.com/reference/kotlin/androidx/compose/ui/layout/OnPlacedModifier#onPlaced(androidx.compose.ui.layout.LayoutCoordinates))
> Add onPlaced to ExceptionsInCompose

- rules/common/src/main/kotlin/io/nlopez/compose/rules/ParameterNaming.kt
- rules/detekt/src/test/kotlin/io/nlopez/compose/rules/detekt/ParameterNamingCheckTest.kt
- rules/ktlint/src/test/kotlin/io/nlopez/compose/rules/ktlint/ParameterNamingCheckTest.kt
See [KeyboardActions.onDone](https://developer.android.com/reference/kotlin/androidx/compose/foundation/text/KeyboardActions#onDone())
> Add onDone to ExceptionsInCompose
